version: "3.9"
services:

  frontend:
    container_name: cinema-frontend
    build:
      context: ./frontend/cinemareservations
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    restart: always

  backend:
    container_name: cinema-backend
    build:
      context: ./backend/CinemaReservations
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:h2:mem:testdb
      - SPRING_DATASOURCE_USERNAME=sa
      - SPRING_DATASOURCE_PASSWORD=
    restart: always

