create sequence admins_seq start with 1 increment by 50;
create sequence cinemas_seq start with 1 increment by 50;
create sequence reservations_seq start with 1 increment by 50;
create sequence rooms_seq start with 1 increment by 50;
create sequence screenings_seq start with 1 increment by 50;
create sequence seat_types_seq start with 1 increment by 50;
create sequence seats_seq start with 1 increment by 50;
create table admins (id integer not null, password varchar(255) not null, username varchar(255) not null, primary key (id));
create table cinemas (id bigint not null, city varchar(255) not null, name varchar(255) not null, primary key (id));
create table reservations (id bigint not null, client_mail varchar(255), screening_id bigint, seat_id bigint, primary key (id));
create table rooms (id bigint not null, name varchar(255) not null, screen_size integer not null, screen_x integer not null, screen_y integer not null, cinema_id bigint not null, primary key (id));
create table screenings (id bigint not null, movie_id bigint not null, time timestamp(6) not null, room_id bigint, primary key (id));
create table screenings_reservations (screening_id bigint not null, reservations_id bigint not null);
create table seat_types (id bigint not null, price float(53) not null, type varchar(255) not null, primary key (id));
create table seats (id bigint not null, seat_row integer not null, room_id bigint, seat_type_id bigint not null, primary key (id));
alter table if exists screenings_reservations add constraint UK_cxwu4rnr7yy4rq5kxbh2mplqn unique (reservations_id);
alter table if exists seat_types add constraint UK_hrroc3d2o4kovmk7h2h66f7us unique (type);
alter table if exists reservations add constraint FKps2fsuvl9g54tk7qitklej8rh foreign key (screening_id) references screenings;
alter table if exists reservations add constraint FK57amums6j9fkqwbpw4oceyw9i foreign key (seat_id) references seats;
alter table if exists rooms add constraint FKjp9bjtvlojbw581bpq23cpw4j foreign key (cinema_id) references cinemas;
alter table if exists screenings add constraint FKq9rxs70hfk4yejjiqw86cxj6t foreign key (room_id) references rooms;
alter table if exists screenings_reservations add constraint FKkgyiqofflcekwtr7sq3bufyq3 foreign key (reservations_id) references reservations;
alter table if exists screenings_reservations add constraint FKfd319yn4g5tiivsvhau5vuy0l foreign key (screening_id) references screenings;
alter table if exists seats add constraint FKg993pi7ucgy616icmddq8u335 foreign key (room_id) references rooms;
alter table if exists seats add constraint FKcp43h11k99445lq681irnensp foreign key (seat_type_id) references seat_types;
